/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.print.PrintService;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import model.Produto;
import service.ImportProduto;
import zebra.ImpressoraZebra;

/**
 *
 * @author jose-ilcle
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());
    
    private String caminho;
    private List<Produto> produtos = new ArrayList<>();
    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        ConfigTabela();
        carregarImpressoras();
    }
    private void ConfigTabela(){
        DefaultTableModel modelo = new DefaultTableModel(
        new Object[][]{},
        new String[]{"Imprimir", "Produto", "Código"}){
        
            @Override
            public Class<?> getColumnClass(int column){
                if(column == 0){
                    return Boolean.class;
                }
                return String.class;
            }
            
            @Override
            public boolean isCellEditable(int row, int column){
                return column == 0;
            }
            
        };
        
        tabelaProdutos.setModel(modelo);
    }
    
    private void preencherTabela(){
        DefaultTableModel modelo = (DefaultTableModel) tabelaProdutos.getModel();
        
        modelo.setRowCount(0);
        
        for (Produto p : produtos) {

            modelo.addRow(new Object[]{
                false,
                p.getNome(),
                p.getCodigo()
            });

        }
    }
    
    private void carregarImpressoras() {

        ImpressoraZebra impressora = new ImpressoraZebra();

        List<PrintService> impressoras = impressora.listarImpressoras();

        Impressoras.removeAllItems();

        for (PrintService ps : impressoras) {
            Impressoras.addItem(ps.getName());
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        caminhoArquivo = new javax.swing.JTextField();
        BuscarArquivo = new javax.swing.JButton();
        ListaPlanilhas = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProdutos = new javax.swing.JTable();
        selecionarPlanilha = new javax.swing.JButton();
        Impressoras = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        imprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        BuscarArquivo.setText("Buscar Aquivo");
        BuscarArquivo.addActionListener(this::BuscarArquivoActionPerformed);

        ListaPlanilhas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ListaPlanilhas.addActionListener(this::ListaPlanilhasActionPerformed);

        jLabel1.setText("Qual planilha sera utilizada");

        tabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Imprimir", "Nome", "Codigo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaProdutos);

        selecionarPlanilha.setText("Selecionar");
        selecionarPlanilha.addActionListener(this::selecionarPlanilhaActionPerformed);

        Impressoras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Impressoras.addActionListener(this::ImpressorasActionPerformed);

        jLabel2.setText("Escolha a Impressora");

        imprimir.setText("Imprimir");
        imprimir.addActionListener(this::imprimirActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(ListaPlanilhas, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(selecionarPlanilha))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(caminhoArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(BuscarArquivo))
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Impressoras, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(imprimir)))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caminhoArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuscarArquivo))
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ListaPlanilhas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selecionarPlanilha))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Impressoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imprimir))
                .addContainerGap(168, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarArquivoActionPerformed
        JFileChooser chooser = new JFileChooser();
        
        int result = chooser.showOpenDialog(this);
        if(result == JFileChooser.APPROVE_OPTION){
            File arquivo = chooser.getSelectedFile();
            
            caminho = arquivo.getAbsolutePath();
            
            caminhoArquivo.setText(caminho);
            ImportProduto produto = new ImportProduto();
            
            List<String> planilhas = produto.listarPlanilhas(caminho);
            ListaPlanilhas.removeAllItems();
            
            for(String planilha : planilhas){
                ListaPlanilhas.addItem(planilha);
            }
        }
        
        
    }//GEN-LAST:event_BuscarArquivoActionPerformed

    private void ListaPlanilhasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaPlanilhasActionPerformed
        
    }//GEN-LAST:event_ListaPlanilhasActionPerformed

    private void selecionarPlanilhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarPlanilhaActionPerformed
        
        int indice = ListaPlanilhas.getSelectedIndex();
        
        ImportProduto leitor = new ImportProduto();
        
        produtos = leitor.importar(caminho, indice);
        
        preencherTabela();
    }//GEN-LAST:event_selecionarPlanilhaActionPerformed

    private void imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imprimirActionPerformed

    private void ImpressorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImpressorasActionPerformed
      
    }//GEN-LAST:event_ImpressorasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarArquivo;
    private javax.swing.JComboBox<String> Impressoras;
    private javax.swing.JComboBox<String> ListaPlanilhas;
    private javax.swing.JTextField caminhoArquivo;
    private javax.swing.JButton imprimir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton selecionarPlanilha;
    private javax.swing.JTable tabelaProdutos;
    // End of variables declaration//GEN-END:variables
}
